"use client";

import React, { useMemo, useState } from "react";

const nav = [
  ["home", "Accueil"],
  ["programmes", "Programmes"],
  ["actualites", "Actualités"],
  ["evenements", "Événements"],
  ["calendrier", "Calendrier"],
  ["client", "Espace client"],
  ["coach", "Cockpit coach"]
];

const programmes = [
  ["🔥", "Transformation 12 semaines", "Premium", "149€ / mois", "Programme structuré avec bilan initial, plan sportif, suivi nutritionnel, messagerie prioritaire et points hebdomadaires."],
  ["🎯", "Coaching individuel", "Sur mesure", "55€ / séance", "Séances personnalisées pour perte de poids, remise en forme, tonification, mobilité ou préparation physique."],
  ["👥", "Bootcamp collectif", "Groupe", "25€ / session", "Sessions dynamiques en petit groupe, challenge cardio, renforcement musculaire et esprit communautaire."]
];

const clients = [
  ["Maya K.", "Perte de poids", 72, "Transformation 12 semaines", "Actif"],
  ["Lucas B.", "Préparation semi-marathon", 54, "Coaching individuel", "Actif"],
  ["Nadia S.", "Renforcement musculaire", 88, "Premium", "Très engagé"],
  ["Olivier T.", "Mobilité & posture", 35, "Suivi visio", "À relancer"]
];

const week = [
  ["Lun", "Bas du corps", "Terminé", "45 min"],
  ["Mar", "Repos actif", "Planifié", "20 min"],
  ["Mer", "Cardio + gainage", "Aujourd’hui", "50 min"],
  ["Jeu", "Mobilité", "Planifié", "30 min"],
  ["Ven", "Full body", "Planifié", "55 min"]
];

const events = [
  ["02", "MAI", "Bootcamp outdoor", "09:30", "6 places restantes"],
  ["07", "MAI", "Atelier nutrition sportive", "18:00", "En ligne"],
  ["16", "MAI", "Challenge cardio & core", "10:00", "12 places restantes"]
];

function cn(...v: Array<string | false | null | undefined>) { return v.filter(Boolean).join(" "); }
function Pill({ children }: { children: React.ReactNode }) { return <span className="inline-flex items-center rounded-full border border-white/15 bg-white/10 px-3 py-1 text-xs font-semibold text-white/85 backdrop-blur">{children}</span>; }
function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <div className={cn("rounded-3xl border border-white/10 bg-white/[0.07] p-6 shadow-2xl shadow-black/20 backdrop-blur-xl", className)}>{children}</div>; }
function Title({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <div className="mx-auto mb-10 max-w-3xl text-center"><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-emerald-400/30 bg-emerald-400/10 px-4 py-2 text-sm font-semibold text-emerald-200">✦ {eyebrow}</div><h2 className="text-3xl font-black tracking-tight text-white md:text-5xl">{title}</h2><p className="mt-4 text-base leading-7 text-slate-300 md:text-lg">{text}</p></div>; }
function Bar({ value }: { value: number }) { return <div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-emerald-300 via-lime-300 to-yellow-300" style={{ width: `${value}%` }} /></div>; }

function Header({ current, setCurrent }: { current: string; setCurrent: (id: string) => void }) {
  const [open, setOpen] = useState(false);
  return <header className="sticky top-0 z-50 border-b border-white/10 bg-slate-950/75 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 md:px-6"><button onClick={() => setCurrent("home")} className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-300 to-lime-300 text-xl text-slate-950">🏋️</span><div className="text-left"><p className="text-base font-black tracking-tight text-white">Coach Serges</p><p className="text-xs font-medium text-slate-400">Performance · Santé · Discipline</p></div></button><nav className="hidden items-center gap-1 lg:flex">{nav.map(([id, label]) => <button key={id} onClick={() => setCurrent(id)} className={cn("rounded-2xl px-4 py-2 text-sm font-semibold transition", current === id ? "bg-white text-slate-950" : "text-slate-300 hover:bg-white/10 hover:text-white")}>{label}</button>)}</nav><div className="hidden items-center gap-3 md:flex"><button onClick={() => setCurrent("client")} className="rounded-2xl border border-white/15 px-4 py-2 text-sm font-bold text-white hover:bg-white/10">Connexion</button><button onClick={() => setCurrent("programmes")} className="rounded-2xl bg-gradient-to-r from-emerald-300 to-lime-300 px-5 py-2.5 text-sm font-black text-slate-950">Réserver →</button></div><button onClick={() => setOpen(!open)} className="rounded-2xl border border-white/10 p-3 text-white lg:hidden">{open ? "✕" : "☰"}</button></div>{open && <div className="border-t border-white/10 bg-slate-950 lg:hidden"><div className="grid gap-2 px-4 py-4">{nav.map(([id, label]) => <button key={id} onClick={() => { setCurrent(id); setOpen(false); }} className={cn("rounded-2xl px-4 py-3 text-left text-sm font-bold", current === id ? "bg-white text-slate-950" : "bg-white/5 text-slate-200")}>{label}</button>)}</div></div>}</header>;
}

function Home({ setCurrent }: { setCurrent: (id: string) => void }) { return <main><section className="px-4 py-16 md:px-6 md:py-24"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.05fr_0.95fr]"><div><div className="mb-6 flex flex-wrap gap-3"><Pill>⚡ Coaching sportif intelligent</Pill><Pill>🛡️ Suivi professionnel sécurisé</Pill></div><h1 className="max-w-5xl text-5xl font-black leading-[0.95] tracking-tight text-white md:text-7xl">Un site premium pour transformer les visiteurs en clients suivis, engagés et fidèles.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300 md:text-xl">Coach Serges réunit une vitrine moderne, une inscription fluide, des programmes de coaching, un calendrier de réservation, une messagerie interne et un cockpit complet.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={() => setCurrent("client")} className="rounded-2xl bg-gradient-to-r from-emerald-300 to-lime-300 px-6 py-4 text-base font-black text-slate-950">Créer un compte client →</button><button onClick={() => setCurrent("coach")} className="rounded-2xl border border-white/15 bg-white/5 px-6 py-4 text-base font-bold text-white">Voir le cockpit coach ▣</button></div></div><Phone /></div></section><section className="px-4 py-16 md:px-6"><div className="mx-auto max-w-7xl"><Title eyebrow="Architecture produit" title="Une plateforme pensée comme un vrai business de coaching" text="Le site gère l’acquisition, la réservation, la relation client, le suivi, les contenus, les événements et l’administration." /><div className="grid gap-5 md:grid-cols-3">{[["●", "Espace client", "Inscription, commandes, calendrier personnel, progression et messages internes."], ["★", "Cockpit coach", "Gestion clients, séances, événements, actualités, paiements, demandes et statistiques."], ["▦", "Planning intelligent", "Calendrier public et privé, disponibilité, réservations, rappels et annulations."], ["✉", "Messagerie interne", "Conversation client/coach, notifications et priorisation."], ["✦", "Conversion premium", "Pages d’offres, CTA, preuves sociales, avis et réservation rapide."], ["▣", "Base solide", "PostgreSQL, OAuth Google/Facebook/TikTok, rôles et déploiement VPS."]].map(([i,t,x]) => <Card key={t}><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-400/15 text-xl text-emerald-200">{i}</div><h3 className="text-xl font-black text-white">{t}</h3><p className="mt-3 leading-7 text-slate-300">{x}</p></Card>)}</div></div></section></main>; }

function Phone() { return <div className="relative mx-auto w-full max-w-sm"><div className="absolute -inset-8 rounded-[3rem] bg-gradient-to-br from-emerald-400/30 via-lime-300/10 to-cyan-400/20 blur-3xl" /><div className="relative overflow-hidden rounded-[2.5rem] border border-white/15 bg-slate-950 p-3 shadow-2xl"><div className="rounded-[2rem] bg-gradient-to-b from-slate-900 to-black p-4"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs text-slate-400">Aujourd’hui</p><p className="text-lg font-black text-white">Plan client</p></div><div className="rounded-full bg-emerald-400/15 p-2 text-emerald-200">🔔</div></div><div className="rounded-3xl bg-gradient-to-br from-emerald-400 to-lime-300 p-5 text-slate-950"><span className="rounded-full bg-black/10 px-3 py-1 text-xs font-bold">Séance du jour</span><h3 className="mt-6 text-2xl font-black">Cardio + Gainage</h3><p className="mt-2 text-sm font-semibold text-slate-800">50 min · intensité modérée · coach en ligne</p></div><div className="mt-4 grid grid-cols-3 gap-2">{[["72%", "Objectif"], ["18", "Séances"], ["4.9", "Score"]].map(([v,l]) => <div key={l} className="rounded-2xl bg-white/5 p-3 text-center"><p className="text-lg font-black text-white">{v}</p><p className="text-[11px] text-slate-400">{l}</p></div>)}</div></div></div></div>; }

function Programmes() { return <main className="px-4 py-16 md:px-6"><div className="mx-auto max-w-7xl"><Title eyebrow="Offres & formations" title="Des programmes lisibles, vendables et administrables" text="Chaque offre peut être créée, modifiée, activée et suivie depuis le panel coach." /><div className="grid gap-6 lg:grid-cols-3">{programmes.map(([i,t,b,p,d]) => <Card key={t} className="h-full"><div className="mb-6 flex items-center justify-between"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-300 to-lime-300 text-2xl text-slate-950">{i}</div><span className="rounded-full bg-white px-3 py-1 text-xs font-black text-slate-950">{b}</span></div><h3 className="text-2xl font-black text-white">{t}</h3><p className="mt-3 min-h-[84px] leading-7 text-slate-300">{d}</p><p className="mt-6 text-3xl font-black text-lime-200">{p}</p><button className="mt-8 w-full rounded-2xl bg-white px-5 py-4 font-black text-slate-950">Commander cette offre</button></Card>)}</div></div></main>; }

function Actualites() { return <main className="px-4 py-16 md:px-6"><div className="mx-auto max-w-7xl"><Title eyebrow="Actualités" title="Un média interne pour attirer, rassurer et convertir" text="Le coach publie conseils, annonces, retours d’expérience, événements, vidéos et articles SEO." /><div className="grid gap-4 md:grid-cols-3">{["Nouvelle méthode Coach Serges", "Comment rester régulier ?", "Ouverture du bootcamp de mai"].map((x) => <Card key={x}><Pill>Actualité</Pill><h3 className="mt-4 text-xl font-black text-white">{x}</h3><p className="mt-3 leading-7 text-slate-300">Contenu administrable depuis le cockpit coach.</p></Card>)}</div></div></main>; }
function Evenements() { return <main className="px-4 py-16 md:px-6"><div className="mx-auto max-w-7xl"><Title eyebrow="Événements" title="Bootcamps, challenges, ateliers et séances spéciales" text="Les événements peuvent être publiés, réservés, modifiés et reliés au calendrier client." /><div className="grid gap-5 md:grid-cols-3">{events.map(([d,m,t,h,s]) => <Card key={t}><div className="flex items-start gap-5"><div className="rounded-3xl bg-white p-4 text-center text-slate-950"><p className="text-3xl font-black">{d}</p><p className="text-xs font-black">{m}</p></div><div><h3 className="text-2xl font-black text-white">{t}</h3><p className="mt-3 text-slate-300">◷ {h}</p><p className="mt-2 text-slate-300">👥 {s}</p></div></div><button className="mt-8 w-full rounded-2xl bg-gradient-to-r from-emerald-300 to-lime-300 px-5 py-4 font-black text-slate-950">Réserver ma place</button></Card>)}</div></div></main>; }
function Calendrier() { return <main className="px-4 py-16 md:px-6"><div className="mx-auto max-w-7xl"><Title eyebrow="Calendrier" title="Réservation claire pour le client, pilotage complet pour le coach" text="Gestion des créneaux disponibles, réservations, annulations, rappels et événements récurrents." /><div className="grid gap-3 md:grid-cols-7">{["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"].map((d,i)=><Card key={d} className="min-h-[220px]"><div className="mb-4 flex items-center justify-between"><p className="font-black text-white">{d}</p><span className="text-xs text-slate-400">{27+i}/04</span></div><div className="space-y-3"><div className="rounded-2xl bg-emerald-400/10 p-3 text-emerald-100">07:30 HIIT</div><div className="rounded-2xl bg-white/5 p-3 text-slate-300">18:30 Bootcamp</div></div></Card>)}</div></div></main>; }
function Client() { return <main className="px-4 py-16 md:px-6"><div className="mx-auto max-w-7xl"><Pill>● Espace utilisateur</Pill><h1 className="mt-4 text-4xl font-black text-white md:text-6xl">Bonjour Maya, votre progression continue.</h1><div className="mt-8 grid gap-5 lg:grid-cols-[0.8fr_1.2fr]"><Card><h3 className="text-xl font-black text-white">Objectif principal</h3><div className="my-6 rounded-3xl bg-gradient-to-br from-emerald-300 to-lime-300 p-5 text-slate-950"><p className="text-sm font-black">Progression globale</p><p className="mt-2 text-5xl font-black">72%</p></div><Bar value={72}/></Card><Card><h3 className="mb-5 text-xl font-black text-white">Mon calendrier sportif</h3>{week.map(([d,w,s,t])=><div key={d} className="mb-3 flex items-center justify-between rounded-3xl border border-white/10 bg-slate-950/55 p-4"><div><p className="font-black text-white">{d} — {w}</p><p className="text-sm text-slate-400">{t}</p></div><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs font-black text-emerald-200">{s}</span></div>)}</Card></div></div></main>; }
function Coach() { return <main className="px-4 py-16 md:px-6"><div className="mx-auto max-w-7xl"><Pill>★ Cockpit coach / super administrateur</Pill><h1 className="mt-4 text-4xl font-black text-white md:text-6xl">Piloter les clients, les contenus, les séances et les ventes.</h1><div className="mt-8 grid gap-4 md:grid-cols-4">{[["Clients actifs","128"],["Séances prévues","42"],["Messages non lus","18"],["CA estimé","8 420€"]].map(([l,v])=><Card key={l}><p className="text-3xl font-black text-white">{v}</p><p className="mt-1 text-sm text-slate-400">{l}</p></Card>)}</div><Card className="mt-5"><h3 className="mb-5 text-2xl font-black text-white">Clients à suivre</h3>{clients.map(([n,o,p,plan,status])=><div key={n} className="mb-3 grid gap-4 rounded-3xl border border-white/10 bg-slate-950/55 p-4 md:grid-cols-[1fr_1fr_0.8fr] md:items-center"><div><p className="font-black text-white">{n}</p><p className="text-sm text-slate-400">{o}</p></div><div><div className="mb-2 flex justify-between text-xs font-bold text-slate-300"><span>{plan}</span><span>{p}%</span></div><Bar value={p as number}/></div><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs font-black text-emerald-200">{status}</span></div>)}</Card></div></main>; }
function Footer() { return <footer className="border-t border-white/10 px-4 py-10 md:px-6"><div className="mx-auto max-w-7xl text-sm font-semibold text-slate-400">Coach Serges — Site officiel et plateforme de coaching.</div></footer>; }

export default function Page() {
  const [current, setCurrent] = useState("home");
  const page = useMemo(() => ({ home: <Home setCurrent={setCurrent}/>, programmes: <Programmes/>, actualites: <Actualites/>, evenements: <Evenements/>, calendrier: <Calendrier/>, client: <Client/>, coach: <Coach/> }[current] || <Home setCurrent={setCurrent}/>), [current]);
  return <div className="min-h-screen bg-slate-950 text-white"><div className="fixed inset-0 -z-10 bg-[radial-gradient(circle_at_top_left,rgba(16,185,129,0.18),transparent_35%),radial-gradient(circle_at_bottom_right,rgba(190,242,100,0.12),transparent_35%)]"/><Header current={current} setCurrent={setCurrent}/>{page}<Footer/></div>;
}
